### ISSUE TITLE
How to get API key?

### ISSUE THREAD

**Issue by eduardsmirnov** [EFA-FHB/ozg-vermittlungsdienst-doku#1]
Hello, looking at BKMS swagger page https://bkms-mediator-app-preview.efa-fhb.apps-int.nortal.com/q/swagger-ui/#/ I see there are two ways of authorization, a token and API key.
I can receive a token using my credentials which I need to do mostly every time I call API.
Is there a way I could get API key to use the same value for all my API calls?

**Comment by JanEisen** [comment]
Hello, 
the api-key based authorization will be deprecated in the near future, so we would recommend to use the token-based approach. If you need the api-key only for testing purposes, this can be arranged. 

tokens are currently valid 24 hours and in the next update (coming in a few days), a refresh token endpoint will be also available.
